services:
  rent-api:
    build:
      context: .
      dockerfile: apps/rent-api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - data-layer
    env_file:
      - apps/rent-api/.env

  data-layer:
    build:
      context: .
      dockerfile: apps/data-layer-service/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - rent-db
    env_file:
      - apps/data-layer-service/.env

  rent-db:
    image: postgres:9.6
    environment:
      LANG: en_US.utf8
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rent-db
    ports:
      - "5432:5432"
    volumes:
      - rent-db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9009:9000"  # host 9009 → container 9000 (S3 API)
      - "9008:9001"  # host 9008 → container 9001 (console)
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

volumes:
  rent-db-data: null
